const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { createRenderer } = require('../lib/render');
const { atomicWrite, cachedRaster } = require('../lib/utils');
const { prune } = require('../lib/cleaner');
test('terminate a hung child and allow queued work to continue', async t => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'qtopo-worker-test-'));
  const renderer = createRenderer({ renderConcurrency: 1, renderQueueLimit: 2, rasterTTL: 10000, emptyTTL: 1000, renderTimeoutMs: 500 }, path.join(__dirname, 'fixtures/render-worker.js'));
  t.after(async () => { renderer.close(); await fs.rm(root, { recursive: true, force: true }); });
  const first = renderer.render({ hang: true, outPath: path.join(root, 'hung.png') });
  const check = assert.rejects(first, { status: 504 });
  const second = renderer.render({ outPath: path.join(root, 'good.png') });
  await check; assert.equal(await second, path.join(root, 'good.png'));
  assert.equal(await fs.readFile(path.join(root, 'good.png'), 'utf8'), 'rendered-test-output');
  await assert.rejects(fs.stat(path.join(root, 'hung.png')), { code: 'ENOENT' });
});
test('empty raster tiles expire even when positive cache lifetime is unlimited', async t => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'qtopo-empty-test-'));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  const blank = path.join(root, 'blank.png'), good = path.join(root, 'good.png');
  await atomicWrite(blank + '.empty', '1'); await atomicWrite(blank, 'blank');
  await atomicWrite(good, 'good');
  assert.equal((await cachedRaster(blank, 0, 1000)).empty, true);
  await fs.utimes(blank, new Date(0), new Date(0)); await fs.utimes(good, new Date(0), new Date(0));
  assert.equal(await cachedRaster(blank, 0, 1000), null);
  assert.equal((await cachedRaster(good, 0, 1000)).empty, false);
  assert.equal(await prune(root, 0, 1000), 1);
  await assert.rejects(fs.stat(blank), { code: 'ENOENT' });
  await assert.rejects(fs.stat(blank + '.empty'), { code: 'ENOENT' });
  assert.equal(await fs.readFile(good, 'utf8'), 'good');
});
