name: Build & Push (Docker Hub)

on:
  push:
    branches: [ master, stable ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          # publish to docker.io/<your-username>/qtopo-server:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qtopo-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
